# -*- coding: utf-8 -*-
"""Aula 6 | Análise Exploratória de Dados sobre Hábitos de Saúde e Bem-Estar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1suQ44enTWGAJBDZfdaPEeBvSNMNqSX

## Análise Exploratória de Dados sobre Hábitos de Saúde e Bem-Estar

**Objetivo do Projeto**

O objetivo é realizar uma análise exploratória de dados sobre hábitos de saúde e bem-estar coletados por meio de um questionário.

A pesquisa foi realizada em outubro de 2025.

**Perguntas de Pesquisa**
* Qual é a frequência de atividade física entre os participantes?
* Qual é o consumo de frutas e bebidas açucaradas semanalmente?
* Existe uma relação entre a prática de atividade física e o consumo de alimentos saudáveis?
* Como variam os padrões de sono e o tempo de tela entre os participantes?
"""

import pandas as pd

dados = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vResfZtKfATsuGT-EgsyFoPaezv8XxIBx_PRpQRd-U3-uyIG2bQzA_-zmp9QEUhz2S6361yOTzsf6h9/pub?gid=373547015&single=true&output=csv")

dados

dados.hist()

dados["Quantos dias por semana você pratica atividades físicas?"].hist()

dados["Quantas porções de frutas você consome em uma semana?"].hist()

"""### Resumo do histograma

* A maioria dos participantes pratica atividade física entre 0 e 1 vez por semana. Isso pode ser visto pela alta frequência de respostas próximas a esses valores.
* Poucos participantes praticam atividade física de maneira mais intensa (de 4 a 7 vezes por semana), sugerindo que uma prática regular de exercícios ainda não é comum entre os respondentes.
* Essa distribuição é muito concentrada em valores baixos, o que pode indicar uma tendência de baixa frequência de atividade física na amostra.
"""

dados["Quantas horas de sono você costuma ter em uma noite durante a semana?"].value_counts()

dados["Quantas bebidas açucaradas (refrigerantes, sucos de caixinha ou energéticos) você consome em uma semana?"].value_counts()